import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard - Mitra Laju Interocean",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body
          className={`${syne.className} antialiased`}
          suppressHydrationWarning
        >
          {children}
          <Toaster 
            richColors
            position="top-center"
            theme="light"
          />
        </body>
      </html>
  );
}
